- name: create user
  hosts: "{{ excute_hosts }}"
#  hosts: "all"
  user: root
  gather_facts: false
  vars:
  - user: "wuzubing"
  tasks:
  - name: create  user
    user: name="{{ user }}"


####
##ansible-playbook -i /etc/ansible/hosts useradd.yml  -e "hosts='172.16.186.129'"
####
####
##post:{"hosts":[{"hostname":"172.16.186.130"},{"hostname":"172.16.186.129"}],"extra_vars":{"excute_hosts":"all","ansible_ssh_user":"root","playbook":"useradd.yml"}}
####