# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-24 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='\u6807\u9898')),
                ('body', models.TextField(verbose_name='\u6b63\u6587')),
                ('timestamp', models.DateTimeField(verbose_name='\u65f6\u95f4')),
                ('author', models.CharField(blank=True, choices=[('\u82cf\u5efa', '\u82cf\u5efa'), ('\u9648\u6865', '\u9648\u6865'), ('\u5f90\u677e', '\u5f90\u677e'), ('\u5434\u78ca', '\u5434\u78ca'), ('\u6c88\u9633', '\u6c88\u9633'), ('\u674e\u541b', '\u674e\u541b'), ('\u5434\u7956\u5175', '\u5434\u7956\u5175')], max_length=64, null=True, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'verbose_name': 'blogs',
                'verbose_name_plural': 'blogs',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5408\u540c\u540d\u79f0')),
                ('csn', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5408\u540c\u53f7')),
                ('jiafang', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7532\u65b9')),
                ('yifang', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u4e59\u65b9')),
                ('producer', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5382\u5546')),
                ('conf', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5178\u914d\u5355')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='\u5408\u540c\u91d1\u989d')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='\u5408\u540c\u8be6\u7ec6')),
                ('file', models.FileField(blank=True, null=True, upload_to=b'upload/contract', verbose_name='\u9644\u4ef6')),
                ('contract_begin_date', models.DateField(blank=True, null=True, verbose_name='\u5408\u540c\u751f\u6548\u65e5\u671f')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='\u5408\u540c\u7ed3\u675f\u65e5\u671f')),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='\u4fdd\u4fee\u5f00\u59cb\u65e5\u671f')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='\u4fdd\u4fee\u7ed3\u675f\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u5408\u540c',
                'verbose_name_plural': '\u5408\u540c',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_type', models.CharField(blank=True, choices=[(b'SAS', b'SAS'), (b'SATA', b'SATA'), (b'SSD', b'SSD'), (b'PCIE', b'PCIE')], max_length=64, null=True, verbose_name='\u786c\u76d8\u7c7b\u578b')),
                ('disk_rev', models.CharField(blank=True, choices=[(b'7.2k', b'7.2k'), (b'10k', b'10k'), (b'15k', b'15k'), (b'others', b'others')], max_length=64, null=True, verbose_name='\u786c\u76d8\u8f6c\u901f')),
                ('disk_size', models.CharField(blank=True, choices=[(b'400G', b'400G'), (b'480G', b'480G'), (b'600G', b'600G'), (b'900G', b'900G'), (b'1T', b'1T'), (b'1.2T', b'1.2T'), (b'1.5T', b'1.5T'), (b'1.8T', b'1.8T'), (b'2T', b'2T'), (b'3.2T', b'3.2T'), (b'4T', b'4T'), (b'6.4T', b'6.4T')], max_length=12, null=True, verbose_name='\u78c1\u76d8\u5bb9\u91cf')),
                ('disk_product', models.CharField(blank=True, choices=[(b'dell', b'Dell'), (b'HP', b'HP'), (b'huawei', b'Huawei'), (b'others', b'others')], max_length=64, null=True, verbose_name='\u5382\u5546')),
                ('disk_num', models.IntegerField(blank=True, null=True, verbose_name='\u603b\u91cf')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='\u65f6\u95f4')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u786c\u76d8',
                'verbose_name_plural': '\u786c\u76d8',
            },
        ),
        migrations.CreateModel(
            name='Disk_rec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_time', models.DateTimeField(blank=True, null=True, verbose_name='\u51fa/\u5165\u5e93\u65f6\u95f4')),
                ('change_stat', models.CharField(blank=True, choices=[('\u51fa\u5e93', '\u51fa\u5e93'), ('\u5165\u5e93', '\u5165\u5e93')], max_length=32, null=True, verbose_name='\u51fa/\u5165\u5e93\u8bb0\u5f55')),
                ('related_servers', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u5173\u8054\u8bbe\u5907(\u591a\u53f0\u8bf7\u7528","\u9694\u5f00)')),
                ('rec_person', models.CharField(blank=True, choices=[('\u82cf\u5efa', '\u82cf\u5efa'), ('\u9648\u6865', '\u9648\u6865'), ('\u5f90\u677e', '\u5f90\u677e'), ('\u5434\u78ca', '\u5434\u78ca'), ('\u6c88\u9633', '\u6c88\u9633'), ('\u674e\u541b', '\u674e\u541b'), ('\u5434\u7956\u5175', '\u5434\u7956\u5175')], max_length=64, null=True, verbose_name='\u8bb0\u5f55\u4eba')),
                ('disk_change', models.IntegerField(blank=True, null=True, verbose_name='\u51fa/\u5165\u6570\u91cf')),
                ('disk_num', models.IntegerField(blank=True, null=True, verbose_name='\u73b0\u6709\u5e93\u5b58')),
                ('memo', models.CharField(blank=True, max_length=120, null=True, verbose_name='\u7ed3\u679c\u5907\u6ce8')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Disk')),
            ],
            options={
                'verbose_name': '\u786c\u76d8\u5e93\u5b58\u8bb0\u5f55',
                'verbose_name_plural': '\u786c\u76d8\u5e93\u5b58\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668\u5206\u7ec4',
                'verbose_name_plural': '\u670d\u52a1\u5668\u5206\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u8d44\u4ea7SN\u53f7')),
                ('brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u54c1\u724c')),
                ('types', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5178\u914d\u7c7b\u578b')),
                ('remarks', models.CharField(blank=True, default=b'None', max_length=200, null=True, verbose_name='\u5907\u6ce8')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Contract', verbose_name='\u5408\u540c')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668\u5e93\u5b58',
                'verbose_name_plural': '\u670d\u52a1\u5668\u5e93\u5b58',
            },
        ),
        migrations.CreateModel(
            name='Ivn_server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u8d44\u4ea7SN\u53f7')),
                ('brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u54c1\u724c')),
                ('types', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5178\u914d\u7c7b\u578b')),
                ('change_time', models.DateTimeField(blank=True, null=True, verbose_name='\u51fa/\u5165\u5e93\u65f6\u95f4')),
                ('change_stat', models.CharField(blank=True, choices=[('\u51fa\u5e93', '\u51fa\u5e93'), ('\u5165\u5e93', '\u5165\u5e93')], max_length=32, null=True, verbose_name='\u51fa/\u5165\u5e93\u8bb0\u5f55')),
                ('rec_person', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u8bb0\u5f55\u4eba')),
                ('change_num', models.IntegerField(blank=True, null=True, verbose_name='\u51fa/\u5165\u6570\u91cf')),
                ('remarks', models.CharField(blank=True, default=b'None', max_length=200, null=True, verbose_name='\u5907\u6ce8')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Contract', verbose_name='\u5408\u540c')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668\u51fa\u5165\u5e93\u8bb0\u5f55',
                'verbose_name_plural': '\u670d\u52a1\u5668\u51fa\u5165\u5e93\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Memery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_type', models.CharField(blank=True, choices=[(b'ddr4', b'ddr4')], max_length=64, null=True, verbose_name='\u5185\u5b58\u7c7b\u578b')),
                ('mem_size', models.CharField(blank=True, choices=[(b'8G', b'8G'), (b'16G', b'16G'), (b'32G', b'32G')], max_length=12, null=True, verbose_name='\u5185\u5b58\u5bb9\u91cf')),
                ('mem_product', models.CharField(blank=True, choices=[(b'dell', b'Dell'), (b'HP', b'HP'), (b'huawei', b'Huawei'), (b'others', b'others')], max_length=64, null=True, verbose_name='\u5382\u5546')),
                ('mem_num', models.IntegerField(blank=True, null=True, verbose_name='\u603b\u91cf')),
                ('mem_create_time', models.DateTimeField(blank=True, null=True, verbose_name='\u65f6\u95f4')),
                ('mem_remark', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u5185\u5b58',
                'verbose_name_plural': '\u5185\u5b58',
            },
        ),
        migrations.CreateModel(
            name='Memery_rec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_time', models.DateTimeField(blank=True, null=True, verbose_name='\u51fa/\u5165\u5e93\u65f6\u95f4')),
                ('change_stat', models.CharField(blank=True, choices=[('\u51fa\u5e93', '\u51fa\u5e93'), ('\u5165\u5e93', '\u5165\u5e93')], max_length=32, null=True, verbose_name='\u51fa/\u5165\u5e93\u8bb0\u5f55')),
                ('related_servers', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u5173\u8054\u8bbe\u5907(\u591a\u53f0\u8bf7\u7528","\u9694\u5f00)')),
                ('rec_person', models.CharField(blank=True, choices=[('\u82cf\u5efa', '\u82cf\u5efa'), ('\u9648\u6865', '\u9648\u6865'), ('\u5f90\u677e', '\u5f90\u677e'), ('\u5434\u78ca', '\u5434\u78ca'), ('\u6c88\u9633', '\u6c88\u9633'), ('\u674e\u541b', '\u674e\u541b'), ('\u5434\u7956\u5175', '\u5434\u7956\u5175')], max_length=64, null=True, verbose_name='\u8bb0\u5f55\u4eba')),
                ('memery_change', models.IntegerField(blank=True, null=True, verbose_name='\u51fa/\u5165\u6570\u91cf')),
                ('memery_num', models.IntegerField(blank=True, null=True, verbose_name='\u73b0\u6709\u5e93\u5b58')),
                ('memo', models.CharField(blank=True, max_length=120, null=True, verbose_name='\u7ed3\u679c\u5907\u6ce8')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Memery')),
            ],
            options={
                'verbose_name': '\u5185\u5b58\u5e93\u5b58\u8bb0\u5f55',
                'verbose_name_plural': '\u5185\u5b58\u5e93\u5b58\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Menber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='\u59d3\u540d')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='\u7535\u8bdd')),
                ('email', models.EmailField(blank=True, max_length=64, verbose_name='Email')),
            ],
            options={
                'verbose_name': '\u6210\u5458',
                'verbose_name_plural': '\u6210\u5458',
            },
        ),
        migrations.CreateModel(
            name='Nic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic_speed', models.CharField(blank=True, choices=[(b'1000Mbps/s', b'1000Mbps/s'), (b'10000Mbps/s', b'10000Mbps/s')], max_length=64, null=True, verbose_name='\u7f51\u5361\u901f\u7387')),
                ('nic_type', models.CharField(blank=True, choices=[('\u5149\u53e3', '\u5149\u53e3'), ('\u7535\u53e3', '\u7535\u53e3')], max_length=12, null=True, verbose_name='\u7f51\u5361\u7c7b\u578b')),
                ('nic_pci', models.CharField(blank=True, choices=[('PCI-\u957f', 'PCI-\u957f'), ('PCI-\u77ed', 'PCI-\u77ed')], max_length=12, null=True, verbose_name='PCI\u5361\u7c7b\u578b')),
                ('nic_num', models.IntegerField(blank=True, null=True, verbose_name='\u7f51\u5361\u603b\u91cf')),
                ('nic_create_time', models.DateTimeField(blank=True, null=True, verbose_name='\u65f6\u95f4')),
                ('nic_remark', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u7f51\u5361',
                'verbose_name_plural': '\u7f51\u5361',
            },
        ),
        migrations.CreateModel(
            name='Nic_rec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_time', models.DateTimeField(blank=True, null=True, verbose_name='\u51fa/\u5165\u5e93\u65f6\u95f4')),
                ('change_stat', models.CharField(blank=True, choices=[('\u51fa\u5e93', '\u51fa\u5e93'), ('\u5165\u5e93', '\u5165\u5e93')], max_length=32, null=True, verbose_name='\u51fa/\u5165\u5e93\u8bb0\u5f55')),
                ('related_servers', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u5173\u8054\u8bbe\u5907(\u591a\u53f0\u8bf7\u7528","\u9694\u5f00)')),
                ('rec_person', models.CharField(blank=True, choices=[('\u82cf\u5efa', '\u82cf\u5efa'), ('\u9648\u6865', '\u9648\u6865'), ('\u5f90\u677e', '\u5f90\u677e'), ('\u5434\u78ca', '\u5434\u78ca'), ('\u6c88\u9633', '\u6c88\u9633'), ('\u674e\u541b', '\u674e\u541b'), ('\u5434\u7956\u5175', '\u5434\u7956\u5175')], max_length=64, null=True, verbose_name='\u8bb0\u5f55\u4eba')),
                ('nic_change', models.IntegerField(blank=True, null=True, verbose_name='\u51fa/\u5165\u6570\u91cf')),
                ('nic_num', models.IntegerField(blank=True, null=True, verbose_name='\u73b0\u6709\u5e93\u5b58')),
                ('memo', models.CharField(blank=True, max_length=120, null=True, verbose_name='\u5907\u6ce8')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Nic')),
            ],
            options={
                'verbose_name': '\u7f51\u5361\u5e93\u5b58\u8bb0\u5f55',
                'verbose_name_plural': '\u7f51\u5361\u5e93\u5b58\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_type', models.CharField(blank=True, choices=[('\u786c\u76d8', '\u786c\u76d8'), ('\u5185\u5b58', '\u5185\u5b58'), ('\u9635\u5217\u5361', '\u9635\u5217\u5361'), ('\u4e3b\u677f', '\u4e3b\u677f'), ('\u7535\u6e90', '\u7535\u6e90'), ('\u5176\u4ed6', '\u5176\u4ed6')], default=b'', max_length=64, null=True, verbose_name='\u6545\u969c\u7c7b\u578b')),
                ('state', models.CharField(blank=True, choices=[(b'A', '\u5df2\u62a5\u4fee\uff0c\u7b49\u5f85\u5382\u5546\u6d3e\u5355'), (b'G', '\u5df2\u6d3e\u5355\uff0c\u7f3a\u914d\u4ef6'), (b'B', '\u786e\u8ba4\u4ea4\u4ed8\u4eba'), (b'C', '\u786e\u8ba4\u505c\u673a\u7ef4\u62a4\u65f6\u95f4'), (b'D', '\u6682\u65f6\u4e0d\u80fd\u505c\u673a'), (b'E', '\u7ef4\u4fee\u540e\uff0c\u6545\u969c\u4f9d\u7136\u5b58\u5728'), (b'F', '\u5b8c\u6210\uff0c\u6545\u969c\u89e3\u9664')], default=b'', max_length=64, null=True, verbose_name='\u5904\u7406\u72b6\u6001')),
                ('discover_time', models.DateTimeField(blank=True, null=True, verbose_name='\u53d1\u73b0\u6545\u969c\u65f6\u95f4')),
                ('report_time', models.DateTimeField(blank=True, null=True, verbose_name='\u62a5\u4fee\u65f6\u95f4')),
                ('report_person', models.CharField(blank=True, choices=[('\u82cf\u5efa', '\u82cf\u5efa'), ('\u9648\u6865', '\u9648\u6865'), ('\u5f90\u677e', '\u5f90\u677e'), ('\u5434\u78ca', '\u5434\u78ca'), ('\u6c88\u9633', '\u6c88\u9633'), ('\u674e\u541b', '\u674e\u541b'), ('\u5434\u7956\u5175', '\u5434\u7956\u5175')], max_length=64, null=True, verbose_name='\u62a5\u4fee\u4eba')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5904\u7406\u6545\u969c\u65f6\u95f4')),
                ('repair_person', models.CharField(blank=True, choices=[('\u82cf\u5efa', '\u82cf\u5efa'), ('\u9648\u6865', '\u9648\u6865'), ('\u5f90\u677e', '\u5f90\u677e'), ('\u5434\u78ca', '\u5434\u78ca'), ('\u6c88\u9633', '\u6c88\u9633'), ('\u674e\u541b', '\u674e\u541b'), ('\u5434\u7956\u5175', '\u5434\u7956\u5175')], max_length=64, null=True, verbose_name='\u5904\u7406\u4eba')),
                ('res', models.CharField(blank=True, choices=[('\u6210\u529f', '\u6210\u529f'), ('\u5931\u8d25', '\u5931\u8d25')], max_length=6, null=True, verbose_name='\u5904\u7406\u7ed3\u679c')),
                ('memo', models.CharField(blank=True, max_length=120, null=True, verbose_name='\u7ed3\u679c\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u7ef4\u4fee\u8bb0\u5f55',
                'verbose_name_plural': '\u7ef4\u4fee\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u8d44\u4ea7SN\u53f7')),
                ('types', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5178\u914d\u7c7b\u578b')),
                ('product', models.CharField(blank=True, max_length=20, verbose_name='\u751f\u4ea7\u5382\u5546')),
                ('manager_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u5e26\u5916\u7ba1\u7406')),
                ('idc_mod', models.CharField(blank=True, choices=[(b'Mod1', b'Mod1'), (b'Mod2', b'Mod2'), (b'Mod3', b'Mod3'), (b'Mod4', b'Mod4'), (b'Ecc', 'Ecc')], max_length=10, null=True, verbose_name='\u6a21\u5757\u673a\u623f')),
                ('cabinet_list', models.CharField(blank=True, choices=[(b'A', b'A'), (b'B', b'B'), (b'C', b'C'), (b'D', b'D'), (b'E', b'E'), (b'F', b'F')], default=b'A', max_length=32, null=True, verbose_name='\u673a\u67dc\u5217')),
                ('cabinet_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u673a\u67dc\u53f7')),
                ('cabinet_begin', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u8d77\u59cbU\u4f4d')),
                ('hostname', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4e3b\u673a\u540d')),
                ('check', models.BooleanField(default=False, verbose_name='\u662f\u5426\u76d1\u63a7')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u63a5\u53e3\u4eba')),
                ('department', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u90e8\u95e8')),
                ('business', models.CharField(blank=True, default=b'None', max_length=50, null=True, verbose_name='\u4e1a\u52a1')),
                ('remarks', models.CharField(blank=True, default=b'None', max_length=200, null=True, verbose_name='\u5907\u6ce8')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Contract', verbose_name='\u5408\u540c')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668',
                'verbose_name_plural': '\u670d\u52a1\u5668',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_content', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u5185\u5bb9\u63cf\u8ff0(\u6ce8:\u6240\u6709\u53d8\u66f4\u5355\u9700\u63d0\u4ea4DCIM\u7cfb\u7edf;)')),
                ('ticket_group', models.CharField(blank=True, choices=[('\u7cfb\u7edf\u7ec4', '\u7cfb\u7edf\u7ec4'), ('\u7f51\u7edc\u7ec4', '\u7f51\u7edc\u7ec4')], default=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe7\xbb\x84', max_length=30, verbose_name='\u5de5\u5355\u5206\u7ec4')),
                ('ticket_source', models.CharField(blank=True, choices=[('\u62a5\u4fee\u8ddf\u8fdb', '\u62a5\u4fee\u8ddf\u8fdb'), ('\u5ba2\u670d\u4f20\u8fbe', '\u5ba2\u670d\u4f20\u8fbe'), ('\u4e0a\u7ea7\u5b89\u6392', '\u4e0a\u7ea7\u5b89\u6392'), ('\u5ba2\u6237\u5bf9\u63a5', '\u5ba2\u6237\u5bf9\u63a5')], max_length=30, null=True, verbose_name='\u5de5\u5355\u6765\u6e90')),
                ('ticket_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('ticket_type', models.CharField(blank=True, choices=[('\u5b9a\u65f6\u5de1\u68c0', '\u5b9a\u65f6\u5de1\u68c0'), ('\u544a\u8b66\u8bb0\u5f55', '\u544a\u8b66\u901a\u62a5(\u5de5\u5355)'), ('\u7cfb\u7edf\u5b89\u88c5', '\u7cfb\u7edf\u5b89\u88c5(\u5de5\u5355)'), ('\u534f\u52a9\u5904\u7406(\u5de5\u5355)', '\u534f\u52a9\u5904\u7406(\u5de5\u5355)'), ('\u8bbe\u5907\u8fc1\u79fb', '\u8bbe\u5907\u8fc1\u79fb(\u53d8\u66f4)'), ('\u7cfb\u7edf\u914d\u7f6e', '\u7cfb\u7edf\u914d\u7f6e(\u53d8\u66f4)'), ('\u8bbe\u5907\u7ef4\u4fee', '\u8bbe\u5907\u7ef4\u4fee(\u53d8\u66f4)'), ('\u8bbe\u5907\u4e0a\u67b6', '\u8bbe\u5907\u4e0a\u67b6(\u53d8\u66f4)'), ('\u8bbe\u5907\u4e0b\u67b6', '\u8bbe\u5907\u4e0b\u67b6(\u53d8\u66f4)'), ('\u589e\u52a0\u5907\u4ef6', '\u589e\u52a0\u5907\u4ef6(\u53d8\u66f4)'), ('\u79fb\u9664\u5907\u4ef6', '\u79fb\u9664\u5907\u4ef6(\u53d8\u66f4)'), ('\u534f\u52a9\u5904\u7406(\u53d8\u66f4)', '\u534f\u52a9\u5904\u7406(\u53d8\u66f4)'), ('\u6280\u672f\u7814\u7a76', '\u6280\u672f\u7814\u7a76')], max_length=30, null=True, verbose_name='\u5de5\u5355\u7c7b\u578b')),
                ('ticket_id', models.CharField(blank=True, default=b'\xe8\x8b\xa5\xe4\xb8\xba\xe5\x8f\x98\xe6\x9b\xb4\xe5\x8d\x95\xef\xbc\x8c\xe8\xaf\xb7\xe8\xbe\x93\xe5\x85\xa5DCIM\xe4\xb8\x8a\xe7\x9a\x84\xe5\x8f\x98\xe6\x9b\xb4\xe5\x8d\x95\xe5\x8f\xb7', max_length=30, verbose_name='\u53d8\u66f4\u5355\u53f7(DCIM\u7cfb\u7edf\u4e0a\u7684\u53d8\u66f4\u5355\u53f7)')),
                ('related_servers', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u6d89\u53ca\u8bbe\u5907SN(\u591a\u53f0\u8bf7\u7528\u7a7a\u683c\u9694\u5f00)')),
                ('server_number', models.IntegerField(blank=True, default=1, null=True, verbose_name='\u6d89\u53ca\u8bbe\u5907\u6570\u91cf')),
                ('executor', models.CharField(blank=True, choices=[('\u82cf\u5efa', '\u82cf\u5efa'), ('\u9648\u6865', '\u9648\u6865'), ('\u5f90\u677e', '\u5f90\u677e'), ('\u5434\u78ca', '\u5434\u78ca'), ('\u6c88\u9633', '\u6c88\u9633'), ('\u674e\u541b', '\u674e\u541b'), ('\u5434\u7956\u5175', '\u5434\u7956\u5175')], max_length=30, verbose_name='\u6267\u884c\u4eba')),
                ('ticket_state', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5b8c\u6210')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5b8c\u6210\u65f6\u95f4')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('menber', models.ManyToManyField(blank=True, to='cmdb.Menber', verbose_name='\u534f\u52a9\u5904\u7406\u4eba')),
            ],
            options={
                'verbose_name': '\u5de5\u5355\u8bb0\u5f55',
                'verbose_name_plural': '\u5de5\u5355\u8bb0\u5f55',
            },
        ),
        migrations.AddField(
            model_name='record',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Server'),
        ),
        migrations.AddField(
            model_name='hostgroup',
            name='members',
            field=models.ManyToManyField(to='cmdb.Server'),
        ),
    ]
